name = "baseballgame"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "baseballgame-db"
database_id = "733c4e44-24bd-4691-b38b-3bf60c611ce2"
